apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose.exe convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Kompose\kompose.exe convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka
    spec:
      containers:
      - args:
        - sh
        - -c
        - bin/kafka-server-start.sh config/server.properties --override listeners=${KAFKA_LISTENERS}
          --override advertised.listeners=${KAFKA_ADVERTISED_LISTENERS} --override
          zookeeper.connect=${KAFKA_ZOOKEEPER_CONNECT} --override listener.security.protocol.map=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
          --override inter.broker.listener.name=${KAFKA_INTER_BROKER_LISTENER_NAME}
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INSIDE://kafka:9093,OUTSIDE://localhost:9092
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INSIDE
        - name: KAFKA_LISTENERS
          value: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        image: strimzi/kafka:0.11.3-kafka-2.1.0
        name: kafka
        ports:
        - containerPort: 9092
        resources: {}
      restartPolicy: Always
status: {}
