apiVersion: v1
kind: Service
metadata:
  name: barista-http-cluster-ip
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 3002
  selector:
    app: barista-http-deployment
  type: ClusterIP